export enum ModalType {
	ASK_INVOICE_DELETE,
	INFO_INVOICE_CREATED,
	INFO_INVOICE_DELETED,
	ERROR_INVOICE_DELETE,
	ERROR_INVOICE_UPDATE,
	ERROR_INVOICE_SAVE,
	ERROR_INVOICEITEM_ADD,
	ERROR_INVOICEITEM_UPDATE,
	ERROR_INVOICEITEM_DELETE
}